# config/routes/framework.yaml
when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

# Aqu√≠ agregas tu archivo de rutas personalizado:
custom_routes:
    resource: 'custom_routes.yaml'
    prefix: /